### PR TITLE
RFC 5285 header extension support

### PR DESCRIPTION
**Pull request by tarrencev**
An initial implementation of RFC 5285 header extensions based on previous work in #17. Please provide feedback :)

This is a breaking change unfortunately. We could probably avoid that with some added complexity if we'd like to.

### CODE REVIEW

**Comment by tarrencev** [comment]
Not sure why the test is failing on `Test WASM 1.13`

**Comment by adwpc** [comment]
> 不知道为什么测试失败 `Test WASM 1.13`
FAIL
402The command "GOOS=js GOARCH=wasm go test \
403  -coverpkg=${coverpkgs} -coverprofile=cover.out -covermode=atomic \
404  -exec="${GO_JS_WASM_EXEC}" \
405  -v ${testpkgs}
406" exited with 1.

**Comment by adwpc** [comment]
LGTM！

**Comment by at-wat** [comment]
```
=== RUN   TestRFC8285MultipleExtensions
--- FAIL: TestRFC8285MultipleExtensions (0.00s)
    packet_test.go:238: Marshal failed raw 
        Marshaled: [144 224 105 143 217 194 147 218 28 100 39 130 190 222 0 3 51 204 204 204 204 16 170 33 187 187 152 54 190 136 158],
        rawPkt:     [144 224 105 143 217 194 147 218 28 100 39 130 190 222 0 3 16 170 33 187 187 51 204 204 204 204 152 54 190 136 158]
```
https://travis-ci.org/github/pion/rtp/jobs/685901555#L276

**Comment by tarrencev** [comment]
I think I fixed the issue and the test didn't run with the new code. I can try trigger it again. Also, the code coverage is better now but that plugin is also having issues. If you click through to the code coverage page you can see. 

@Sean-Der how would you like to handle this PR since it is a breaking change?

**Comment by tarrencev** [comment]
The reason the tests are flaky is the iteration order of a map is not guaranteed. So i think we should switch Extensions to use an array instead.

**Comment by tarrencev** [comment]
I've added back `ExtensionPayload` for RFC3550 extensions. This makes these changes backward compatible. Hopefully that means we can merge them into master 😁

**Comment by tarrencev** [comment]
I think this is good to go!

**Pull request merged**
