### PR TITLE
Add padding support to Packetizer

### PR DESCRIPTION
**Pull request by alexpokotilo**
To add padding-only samples call GeneratePadding

#### Description
Sometime for Bandwidth estimation purposes we need to add Padding-only packages to the stream before switching to new rendition. Once this branch merges I will add pull request to add necessary support to TrackLocalStaticSample in webrtc repo.

### CODE REVIEW

**Comment by Sean-Der** [comment]
@alexpokotilo LGTM! What do you think of different name like `CreatePadding` or `GeneratePadding`. 

I didn't understand the purpose of the function until I read the code.

**Comment by alexpokotilo** [comment]
> @alexpokotilo LGTM! What do you think of different name like `CreatePadding` or `GeneratePadding`.
> 
> I didn't understand the purpose of the function until I read the code.
Sean,
thanks for your feedback.
I've changed to GeneratePadding.

**Comment by Sean-Der** [comment]
Merged! Thank you so much @alexpokotilo 

Can I add you to the Pion org? You can create branches and will run tests for you. Would love to work closer together!

**Comment by alexpokotilo** [comment]
> Merged! Thank you so much @alexpokotilo
> 
> Can I add you to the Pion org? You can create branches and will run tests for you. Would love to work closer together!

@Sean-Der 
It's a great honor to be part of Pion org! You can definitely add me.

**Comment by alexpokotilo** [comment]
@Sean-Der,
as I've said I have some delta in webrtc repository https://github.com/alexpokotilo/webrtc/tree/static-sample-padding-support to support padding in TrackLocalStaticSample. To pull merge request I need:
1) new rtp version with tag 1.8.4 releases
2) pion/master and pion/v3 upgraded rtp to 1.8.4 dependencies.
I'll file two merge requests for pion/master and for pion/v3.
I can upgrade go.mod for pion/v3 and pion/master myself but I need 1.8.4 to be released in anyway. Sorry for bothering you

**Comment by Sean-Der** [comment]
You are never bothering me! I really appreciate you being involved :) I am sorry I am so slow to respond!

Ping me in the [Pion Slack](https://pion.ly/slack) that is much lower volume and I will respond instantly. Email/GitHub is hard for me because I get so much it is hard to filter

**Pull request merged**
