### PR TITLE
Remove the IsDetectedFinalPacket method from Depacketizer

### LINKED ISSUE #139: Interface change breaks existing code
Revision #34c6ce978ad576469ea43860fecc48fad612c7c8 added a new method to the Depacketizer interface, thus breaking all existing code that implements a Depacketizer.

The method itself was introduced in #9e081b57389c3b1d859971912cb7e8e3d194d1cc, and is basically a verbose and error-prone way of saying
```
if codec is video {
     return packet.Mark
}
return true
```
I therefore recommend that both changes above should be reverted.  If the functionality is needed (which I doubt), it should be implemented by checking whether the codec is doing video, and doing the right thing without imposing an extra method on all depacketisers, which is difficult to check and causes massive code duplication.

### PR DESCRIPTION
**Pull request by jech**
Not only does this break all code that attempts to implement
a depacketizer, it is just a very verbose and error-prone way
of saying

  if codec is video {
      return packet.Mark
  }
  return true

It is better to check the codec type at the calling site rather
than imposing a new method on all depacketisers, which causes
code duplication and is very difficult to check.

Fixes #139.

### CODE REVIEW

**Comment by jech** [comment]
CC @robin-raymond

**Comment by jech** [comment]
Please see https://github.com/jech/samplebuilder which implements the exact same functionality without forcing an extra method for all implementers of depacketizer.

**Comment by jech** [comment]
See https://github.com/pion/webrtc/pull/1882 for a clean implementation of the same functionality.

**Comment by Sean-Der** [comment]
@jech One downside of this is that this requires users to configure the `SampleBuilder`. Do you see any benefits of configuration being bundled with the codec?

**Comment by jech** [comment]
There are two possible choices:
  1. partition boundaries are the responsibility of the codec;
  2. partition boundaries are the responsibility of the caller.
Right now, we are inconsistent: partition heads are the responsibility of the caller (WithPartitionHeadChecker), while partition tails are the responsibility of the codec.

Pull request https://github.com/pion/webrtc/pull/1882 makes things consistent again by moving parition tail checking into the caller (case (2) above).  This has the advantage of a consistent API and of only using a small number of well-defined interfaces.  The disadvantage is that the caller needs to pass the right partition head and tail checkers to each sample builder.

If there is a strong consensus in favour of making things automatic (which I dislike, too much magic makes code undebuggable), then I can try to think about how to do that cleanly, without adding a new method to each and every new codec (C++ style).

**Comment by Sean-Der** [comment]
I am in favor of making things automatic (having an interface)

* Most users will not be implementing their own codecs. I don't want to require boilerplate code for the SampleBuilder to work for them.
* For developers who wish to customize a codec they can embed and provide their own methods
* For developers who wish to implement their own codecs entirely I can see the frustration. 

I took a look through github at the users of SampleBuilder and that felt to line up with most users. I don't have much data (or user interviews I can pull from). If this blocks you from implementing anything @jech I am happy to re-visit. 

I am sorry that we provide the interface and didn't bump the API. It is unfortunate, will try to set up tooling so it doesn't happen again.

**Pull request closed without merging**
